# ===================================================================
# Spring Boot Configuration for the dev profile
# ===================================================================

# SERVER
server:
  domain-name: http://localhost:8080
  error:
    include-exception: true # Include the "exception" attribute.
    include-stacktrace: always # When to include a "stacktrace" attribute.
    whitelabel.enabled: true

# LOGGING
logging:
  level:
    root: INFO
    com.oksusu: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: DEBUG
    reactor.netty.http.client: DEBUG

# SPRING
spring:
  config:
    import:
      - aws-parameterstore:/susu/api-server_dev/
  jackson:
    serialization:
      indent_output: true
      write-null-map-values: true
  data:
    redis:
      host: localhost
      port: 6379

# DEV-DATABASE-COMMON
datasource: &dev-datasource
  url: jdbc:mysql://localhost:3306/susu?useUnicode=true&charset=utf8mb4&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
  username: susu
  password: susu
  hikari:
    minimum-idle: 2
    maximum-pool-size: 2

# DATABASE
susu:
  master.datasource: *dev-datasource
  jpa:
    properties:
      hibernate.format_sql: true
      hibernate.hbm2ddl.auto: none
  maximum-jdbc-thread-pool-size:

# OAUTH
oauth:
  kakao:
    withdraw-callback-url: ${KAKAO_WITHDRAW_CALLBACK_URL}
    unlink-url: ${KAKAO_UNLINK_URL}
    user-info-url: ${KAKAO_USER_INFO_URL}
    authorize-url: ${KAKAO_AUTHORIZE_URL}
    token-url: ${KAKAO_TOKEN_URL}
    kauth-url: ${KAKAO_KAUTH_URL}
    kapi-url: ${KAKAO_KAPI_URL}
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-url: ${KAKAO_REDIRECT_URL}
    app-key: ${KAKAO_APP_KEY}
    admin-key: ${KAKAO_ADMIN_KEY}

# AUTH
auth:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-exp: ${JWT_ACCESS_EXP}
    refresh-exp: ${JWT_REFRESH_EXP}
