# ===================================================================
# Spring Boot Configuration for the default profile
# ===================================================================

# SERVER
server:
  port: 8080
  http2:
    enabled: true
  shutdown: graceful # timeout configuration property : spring.lifecycle.timeout-per-shutdown-phase

logging:
  level:
    root: INFO

# SPRING
spring:
  lifecycle:
    timeout-per-shutdown-phase: 5s # format : https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config-conversion-duration
  application:
    name: oksusu-susu-api
  data:
    redis:
      repositories:
        enabled: false

# DOCS
springdoc:
  swagger-ui:
    operations-sorter: alpha
  model-and-view-allowed: true
  packages-to-scan: com.oksusu.susu

# DATABASE
susu:
  master:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate.default_batch_fetch_size: 10
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibrenate.jdbc.batch_size: 50
      hibernate.jdbc.batch_versioned_data: true
      hibernate.jdbc.time_zone: Asia/Seoul
      hibernate.hbm2ddl.auto: none
    show-sql: false
    database: mysql

# AUTH
auth:
  jwt:
    secret-key: 27a68785a3597923c505668253cbad2ce42adfbac558611b272aa44684436e7e6a4f83a59bf89cf413a957638a4558acd58dac5d8da497d6e84fa08094ee2203
