# ===================================================================
# Spring Boot Configuration for the prod profile
# ===================================================================

# SERVER
server:
  domain-name: ${SERVER_DOMAIN_NAME}
  error:
    include-exception: true # Include the "exception" attribute.
    include-stacktrace: always # When to include a "stacktrace" attribute.
    whitelabel.enabled: true

# LOGGING
logging:
  level:
    root: INFO

# SPRING
spring:
  config:
    import:
      - aws-parameterstore:/susu/api-server_prod/
  jackson:
    serialization:
      indent_output: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

# DATABASE
susu:
  master:
    datasource:
      url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DB_NAME}?useUnicode=true&charset=utf8mb4&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: ${MYSQL_USERNAME}
      password: ${MYSQL_PASSWORD}
      hikari:
        minimum-idle: 10
        maximum-pool-size: 15
  jpa:
    properties:
      hibernate.format_sql: true
      hibernate.hbm2ddl.auto: none
  maximum-jdbc-thread-pool-size:

# OAUTH
oauth:
  kakao:
    withdraw-callback-url: ${KAKAO_WITHDRAW_CALLBACK_URL}
    unlink-url: ${KAKAO_UNLINK_URL}
    user-info-url: ${KAKAO_USER_INFO_URL}
    authorize-url: ${KAKAO_AUTHORIZE_URL}
    token-url: ${KAKAO_TOKEN_URL}
    kauth-url: ${KAKAO_KAUTH_URL}
    kapi-url: ${KAKAO_KAPI_URL}
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-url: ${KAKAO_REDIRECT_URL}
    app-key: ${KAKAO_APP_KEY}
    admin-key: ${KAKAO_ADMIN_KEY}

# AUTH
auth:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-exp: ${JWT_ACCESS_EXP}
    refresh-exp: ${JWT_REFRESH_EXP}

# SLACK
slack:
  alarm:
    error-webhook:
      url: ${SLACK_ALARM_ERROR_URL}
      text: ${SLACK_ALARM_ERROR_TEXT}
      user-name: ${SLACK_ALARM_ERROR_USERNAME}
  token: ${SLACK_TOKEN}

# SENTRY
sentry:
  dsn: ${SENTRY_DSN}
  traces-sample-rate: 1.0
  enable-tracing: true
  environment: prod
  serverName: api-server
  send-default-pii: true
