# Susu Config

susu:
  envelop-config:
    create-form:
      min-amount: 0
      max-amount: 9999999999
      max-gift-length: 100
      max-memo-length: 200
  category-config:
    create-form:
      max-custom-category-length: 100
  ledger-config:
    create-form:
      only-start-at-category-ids:
        - 1
        - 2
        - 4
        - 5
      min-title-length: 1
      max-title-length: 50
      max-description-length: 100
  post-config:
    create-form:
      max-title-length: 250
      min-content-length: 1
      max-content-length: 500
    create-vote-form:
      min-option-count: 1
    create-vote-option-form:
      min-content-length: 1
      max-content-length: 100
  onboarding-config:
    get-vote:
      vote-id: 1
