# ===================================================================
# Spring Boot Configuration for the default profile
# ===================================================================

# DATABASE
susu:
  master:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate.default_batch_fetch_size: 10
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibrenate.jdbc.batch_size: 50
      hibernate.jdbc.batch_versioned_data: true
      hibernate.jdbc.time_zone: Asia/Seoul
      hibernate.hbm2ddl.auto: none
    show-sql: false
    database: mysql

---
# ===================================================================
# Spring Boot Configuration for the dev profile
# ===================================================================
spring:
  config:
    activate:
      on-profile: dev

  # REDIS
  data:
    redis:
      host: localhost
      port: 6379

# DEV-DATABASE-COMMON
datasource: &dev-datasource
  url: jdbc:mysql://localhost:3306/susu?useUnicode=true&charset=utf8mb4&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
  username: susu
  password: susu
  hikari:
    minimum-idle: 2
    maximum-pool-size: 2

# DATABASE
susu:
  master.datasource: *dev-datasource
  jpa:
    properties:
      hibernate.format_sql: true
      hibernate.hbm2ddl.auto: none
  maximum-jdbc-thread-pool-size:

---
# ===================================================================
# Spring Boot Configuration for the prod profile
# ===================================================================
spring:
  config:
    activate:
      on-profile: prod

  # REDIS
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

# PROD-DATABASE-COMMON
datasource: &prod-datasource
  url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DB_NAME}?useUnicode=true&charset=utf8mb4&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
  username: ${MYSQL_USERNAME}
  password: ${MYSQL_PASSWORD}
  hikari:
    minimum-idle: 15
    maximum-pool-size: 25

# DATABASE
susu:
  master.datasource: *prod-datasource
  jpa:
    properties:
      hibernate.format_sql: true
      hibernate.hbm2ddl.auto: none
  maximum-jdbc-thread-pool-size:
