# ===================================================================
# Spring Boot Configuration for the dev profile
# ===================================================================

# DEV-DATABASE-COMMON
datasource: &dev-datasource
  url: jdbc:mysql://localhost:3306/susu?useUnicode=true&charset=utf8mb4&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
  username: susu
  password: susu
  hikari:
    minimum-idle: 2
    maximum-pool-size: 2

# DATABASE
susu:
  master.datasource: *dev-datasource
  jpa:
    properties:
      hibernate.format_sql: true
      hibernate.hbm2ddl.auto: none
  maximum-jdbc-thread-pool-size:

# REDIS
spring:
  data:
    redis:
      host: localhost
      port: 6379