# ===================================================================
# Spring Boot Configuration for the prod profile
# ===================================================================

# SERVER
server:
  domain-name: ${SERVER_DOMAIN_NAME}
  error:
    include-exception: true # Include the "exception" attribute.
    include-stacktrace: always # When to include a "stacktrace" attribute.
    whitelabel.enabled: true

# LOGGING
logging:
  level:
    root: INFO

# SPRING
spring:
  config:
    import:
      - 'aws-parameterstore:/susu/api-server_prod/'
  jackson:
    serialization:
      indent_output: true

# SENTRY
sentry:
  dsn: ${SENTRY_DSN}
  traces-sample-rate: 1.0
  enable-tracing: true
  environment: prod
  serverName: api-server
  send-default-pii: true
