# ===================================================================
# Spring Boot Configuration for the default profile
# ===================================================================

---
# ===================================================================
# Spring Boot Configuration for the dev profile
# ===================================================================
spring:
  config:
    activate:
      on-profile: dev

---
# ===================================================================
# Spring Boot Configuration for the prod profile
# ===================================================================
spring:
  config:
    activate:
      on-profile: prod