# ===================================================================
# Spring Boot Configuration for the prod profile
# ===================================================================

# OAUTH
oauth:
  kakao:
    withdraw-callback-url: ${KAKAO_WITHDRAW_CALLBACK_URL}
    unlink-url: ${KAKAO_UNLINK_URL}
    user-info-url: ${KAKAO_USER_INFO_URL}
    authorize-url: ${KAKAO_AUTHORIZE_URL}
    token-url: ${KAKAO_TOKEN_URL}
    kauth-url: ${KAKAO_KAUTH_URL}
    kapi-url: ${KAKAO_KAPI_URL}
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-url: ${KAKAO_REDIRECT_URL}
    app-key: ${KAKAO_APP_KEY}
    admin-key: ${KAKAO_ADMIN_KEY}

# AUTH
auth:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-exp: ${JWT_ACCESS_EXP}
    refresh-exp: ${JWT_REFRESH_EXP}