# ===================================================================
# Spring Boot Configuration for the default profile
# ===================================================================

spring:
  config:
    import:
      - classpath:/susu-config.yml

---
# ===================================================================
# Spring Boot Configuration for the dev profile
# ===================================================================
spring:
  config:
    activate:
      on-profile: dev

---
# ===================================================================
# Spring Boot Configuration for the prod profile
# ===================================================================
spring:
  config:
    activate:
      on-profile: prod