# ===================================================================
# Spring Boot Configuration for the default profile
# ===================================================================
slack:
  webhook:
    summary-token: ${SLACK_SUMMARY_TOKEN}
    error-token: ${SLACK_ERROR_TOKEN}
    warning-log-token: ${SLACK_WARNING_LOG_TOKEN}

# OAUTH
oauth-url:
  kakao:
    withdraw-callback-url: ${KAKAO_WITHDRAW_CALLBACK_URL}
    unlink-url: ${KAKAO_UNLINK_URL}
    user-info-url: ${KAKAO_USER_INFO_URL}
    authorize-url: ${KAKAO_AUTHORIZE_URL}
    token-url: ${KAKAO_TOKEN_URL}
    kauth-url: ${KAKAO_KAUTH_URL}
    kapi-url: ${KAKAO_KAPI_URL}
    redirect-url: ${KAKAO_REDIRECT_URL}

  apple:
    apple-id-url: ${APPLE_APPLEID_URL}
    dev-callback-url: ${APPLE_DEV_CALLBACK_URL}
    withdraw-callback-url: ${APPLE_WITHDRAW_CALLBACK_URL}
    authorize-url: ${APPLE_AUTHORIZE_URL}
    token-url: ${APPLE_TOKEN_URL}
    oidc-key-url: ${APPLE_OIDC_KEY_URL}
    withdraw-url: ${APPLE_WITHDRAW_URL}

  google:
    withdraw-callback-url: ${GOOGLE_WITHDRAW_CALLBACK_URL}
    revoke-url: ${GOOGLE_REVOKE_URL}
    user-info-url: ${GOOGLE_USER_INFO_URL}
    authorize-url: ${GOOGLE_AUTHORIZE_URL}
    token-url: ${GOOGLE_TOKEN_URL}
    account-google-url: ${GOOGLE_ACCOUNT_GOOGLE_URL}
    oauth2-google-api-url: ${GOOGLE_OAUTH2_GOOGLE_API_URL}
    google-api-url: ${GOOGLE_GOOGLE_API_URL}
    redirect-url: ${GOOGLE_REDIRECT_URL}

---
# ===================================================================
# Spring Boot Configuration for the dev profile
# ===================================================================
spring:
  config:
    activate:
      on-profile: dev

---
# ===================================================================
# Spring Boot Configuration for the prod profile
# ===================================================================
spring:
  config:
    activate:
      on-profile: prod