name: CI

on:
  pull_request:
    branches:
      - develop
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kotlin-version: [ "1.8.22" ]
        java-version: [ "11" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Kotlin
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          kotlin-version: ${{ matrix.kotlin-version }}
          distribution: 'adopt'

      # 자동 Ktlint 체크 자동화
      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          ktlint_version: "1.8.22"
#          fail_on_error: true # 오류 발생시 실패